////////////////////////////////////////////////////////////////
//
// LRM:         SV2012
// Page:        274
// Description: violation reports generated by unique-case
// Note:        
//
////////////////////////////////////////////////////////////////

module sv12_lrm_p0274_always_comb_begin;

  logic not_a,a,b,c,z;

  always_comb begin
    not_a = !a;
  end
  
  always_comb begin : a1
    unique case (1'b1)
      a     : z = b;
      not_a : z = c;
    endcase
  end
  
  task task1; endtask
  task task2; endtask
  logic [2:0] status;
  logic clock;
  always @(posedge clock)
    priority case (status) inside
      1, 3 : task1; // matches 'b001 and 'b011
      3'b0?0, [4:7]: task2; // matches 'b000 'b010 'b0x0 'b0z0
                            // 'b100 'b101 'b110 'b111
    endcase // priority case fails all other values including
            // 'b00x 'b01x 'bxxx

endmodule : sv12_lrm_p0274_always_comb_begin
