////////////////////////////////////////////////////////////////
//
// LRM:         SV2012
// Page:        268
// Description: violation reports generated by unique-if
// Note:        
//
////////////////////////////////////////////////////////////////

module sv12_lrm_p0268_always_comb_begin;
  logic not_a,a,b,c,z;

  always_comb begin
    not_a = !a;
  end
  
  always_comb begin : a1
    u1: unique if (a)
      z = a | b;
	else if (not_a)
      z = a | c;
  end
  
  logic [3:0] not_aa,aa;
  always_comb begin
    for (int j = 0; j < 3; j++)
      not_aa[j] = !aa[j];
  end

endmodule : sv12_lrm_p0268_always_comb_begin
